export const projectData = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description:
      "A full-stack e-commerce solution with user authentication, product management, and payment integration. Features include real-time inventory tracking, secure payment processing, and an intuitive admin dashboard.",
    technologies: [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
      "Redux",
      "Stripe",
      "JWT",
    ],
    category: "Full Stack",
    image: "https://placehold.co/600x400/pink/white?text=E-Commerce",
    githubLink: "https://github.com",
    liveLink: "https://demo.com",
    highlights: [
      "User authentication and authorization",
      "Payment gateway integration",
      "Real-time inventory management",
      "Responsive design",
    ],
  },
  {
    id: 2,
    title: "Task Management App",
    description:
      "A collaborative task management tool with real-time updates and team workspace features. Includes drag-and-drop task organization, deadline tracking, and team collaboration tools.",
    technologies: [
      "React",
      "Firebase",
      "Tailwind CSS",
      "React DnD",
      "Redux Toolkit",
    ],
    category: "Web App",
    image: "https://placehold.co/600x400/pink/white?text=Task+Manager",
    githubLink: "https://github.com",
    liveLink: "https://demo.com",
    highlights: [
      "Real-time collaboration",
      "Drag and drop interface",
      "Team workspaces",
      "Progress tracking",
    ],
  },
  {
    id: 3,
    title: "Social Media Dashboard",
    description:
      "Analytics dashboard for social media metrics with data visualization and reporting features. Provides comprehensive insights through interactive charts and customizable reports.",
    technologies: [
      "React",
      "Chart.js",
      "Node.js",
      "MongoDB",
      "Socket.io",
      "Material UI",
    ],
    category: "Analytics",
    image: "https://placehold.co/600x400/pink/white?text=Dashboard",
    githubLink: "https://github.com",
    liveLink: "https://demo.com",
    highlights: [
      "Real-time analytics",
      "Interactive data visualization",
      "Custom report generation",
      "Multi-platform integration",
    ],
  },
  {
    id: 4,
    title: "Portfolio Website",
    description:
      "A modern, responsive portfolio website showcasing my projects and skills. Built with React and features smooth animations, dark mode, and contact form integration.",
    technologies: ["React", "Tailwind CSS", "Framer Motion", "EmailJS"],
    category: "Frontend",
    image: "https://placehold.co/600x400/pink/white?text=Portfolio",
    githubLink: "https://github.com",
    liveLink: "https://demo.com",
    highlights: [
      "Responsive design",
      "Smooth animations",
      "Dark/Light mode",
      "Contact form integration",
    ],
  },
];
